### ISSUE TITLE
display on job configuration is a bit annoying, it shall be optimized

### ISSUE THREAD

**Issue by ukuko** [jenkinsci/office-365-connector-plugin#178]
the plugin doesn't have a marker to show end of its scope, confusing people who doesn't work with the plugin at all.

an easy way would be to add a bar ("_____________________") after the plugins fields (in below screenshot, it is before "Use default Jenkins load balancer")

![2019-09-18 23_35_31-buil-devkit Config  Jenkins](https://user-images.githubusercontent.com/3519010/65187810-1596b700-da6d-11e9-817c-2e688fd8649b.png)

**Comment by damianszczepanik** [comment]
I don't understand

**Comment by ukuko** [comment]
hi Damian, I mean something like attached picture, to clearly mark end of plugin settings.
![2019-09-20 00_27_30-Untitled - Paint](https://user-images.githubusercontent.com/3519010/65285729-a046e700-db3d-11e9-9f14-c1fc49fdf6df.png)

**Comment by damianszczepanik** [comment]
As you see background is different and other plugins don't put separator do I won't do as well

**Comment by marcjay** [comment]
I think this issue is valid - other plugins don't introduce a whole new section to the job configuration screen (I would argue this plugin shouldn't either) but on the basis that it does, I do think it should have a separator:
![image](https://user-images.githubusercontent.com/580744/73679622-adaadb00-46b2-11ea-8f5a-6bec89181b1b.png)

e.g. Source Code Management
![image](https://user-images.githubusercontent.com/580744/73679690-cf0bc700-46b2-11ea-97d8-91c367ccf6e6.png)

**Comment by damianszczepanik** [comment]
Source Code Management - as you can see at the navigation bar you posted - is not just plugin, this is whole section of the configuration. So it's different story
