### ISSUE TITLE
How to send notifications - only on a specific branch?

### ISSUE THREAD

**Issue by iptizer** [jenkinsci/office-365-connector-plugin#252]
### Feature Request

Objective: Only send notifications when on a specific branch (e.g. `master`).

I would configure the Jenkinsfile with the following option. Webhook url is configured globally:

```
options {
        office365ConnectorWebhooks([[
                timeout: 30000,
                startNotification: false,
                notifyFailure: true,
                notifyBackToNormal: true,
                notifyRepeatedFailure: true,
                notifyNotBuilt: true,
                notifyUnstable: true
            ]]
        )
    }
```

Unfortunately *options* does not understand conditionals. So how would this be done?

Thanks in advance! I'm aware, this is not directly related to the plugin itself, but I'd highly appreciate some guidance nevertheless. Thx!

**Comment by damianszczepanik** [comment]
I don't know if this section is supported by if-condition but for sure this is not the plugin responsibility.

**Comment by mike-pt** [comment]
Is there any change this can be reconsidered as a feature?

This section does support if for sure (this is for declarative pipeline), with scripted maybe but since this is set in properties I not so sure we can either...

If the plugin works only on "steps" as other (slack i.e.) that this would be more flexible, sure this way it also makes it more simple to just set it up overall, but who want notification of builds FOR ALL branches, and even if you do maybe you would want them in different Teams? 

If the plugin is doing this via options/properties there's no other place where it can be implemented by us in the Jenkinsfile.

I was wondering if this could be set using "macros" but I think that's just for scripted to correct?

**Comment by damianszczepanik** [comment]
With pipeline you can do whatever you want, including if/else against branch name

https://github.com/jenkinsci/office-365-connector-plugin/blob/master/README.md

**Comment by mike-pt** [comment]
"with pipeline"?

I'm not sure I follow...

With scripted pipeline? But we are talking about declarative, and I still haven't found a reference to that in the doc.. am I missing something?

Regardless one can't use "ifs" in "properties" step (scripted) nor "options" (declarative).

If's can be used latter in scripted pipeline, but not declarative, in declarative pipeline the syntax is limited, it does have the option to add "script" steps but that wouldn't help here either.

**Comment by wozprzemek** [comment]
Based on the example with "Conditioning webhook trigger on build parameter (...)" from the readme, is it possible to use macros for specifying the branch?

**Comment by damianszczepanik** [comment]
what ever macro plugin supports
