### ISSUE TITLE
Custom message with Freestyle project

### ISSUE THREAD

**Issue by xfreebird** [jenkinsci/office-365-connector-plugin#75]
Hi,

Is there a way to customize sent message for regular freestyle project (e.g. no pipeline script) ?
Can't find this option in the plugin job configuration.

Thanks,
Nicolae

**Comment by Lynderyn** [comment]
I also am unable to find a way to do this.  It would be nice to have a set-up like the HipChat integration where you can select a color and custom message template for each of the different build statuses.

**Comment by Pe-te** [comment]
Hey folks, I saw some very nice ideas to compact the output in this blog, for example duration instead of two timestamps:
https://medium.com/existek/how-to-improve-jenkins-notifications-ux-design-in-microsoft-teams-d689894928db
Would be nice to have "compact format" or even the single changes as checkboxes in jenkins.
Maybe this is related to what you do?

**Comment by damianszczepanik** [comment]
Most of those features will be provided soon

**Comment by Pe-te** [comment]
Very nice, thank you!

**Comment by spencer-edh** [comment]
Any update on this? I would really appreciate this feature. The HipChat integration is nice and we are moving to teams so having this type of integration on freestyle projects for teams is necessary for us.

**Comment by damianszczepanik** [comment]
Wait for next release

**Comment by n1kl** [comment]
would it be possible to replace 
Status -> Build Unstable
Remarks -> Started by remote host 192.168
by the new Facts with Token Macro and not having this shown by default. I would like be make it more compact and Remarks has no relevant information for me.
